# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-easyorder
# spec:
#   type: NodePort
#   selector:
#     app: easyorder
#   ports:
#   - port: 30000
#     targetPort: 30000
#     nodePort: 30000

apiVersion: v1
kind: Service
metadata:
  name: svc-easyorder
spec:
  type: LoadBalancer
  selector:
    app: easyorder
  ports:
  - port: 80
    targetPort: 30000